spring.application.name=AIS_SST
spring.datasource.url=jdbc:postgresql://localhost:5432/AIS_SST?stringtype=unspecified
spring.datasource.username=coffee13102006
spring.datasource.password=nata155630
spring.datasource2.initialization-mode=always
spring.datasource2.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.hibernate.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
