# ????? ????? ?? ????????? ??? ? local ???????
spring.application.name=AIS_SST
server.port=8080

# Database - ?????? host ??????????
spring.datasource.url=jdbc:postgresql://postgres:5432/AIS_SST?stringtype=unspecified
spring.datasource.username=coffee13102006
spring.datasource.password=nata155630
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - ???????? ?????????
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwtSecret=mySecretKeyForJWTGenerationWithAtLeast32CharactersLong2024!
app.jwtExpirationMs=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.example.ais_sst=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type=TRACE

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

