# ????? ????? ?? ????????? ??? ? local ???????
spring.application.name=AIS_SST
server.port=8080

# Database - ?????? host ??????????
spring.datasource.url=jdbc:postgresql://postgres:5432/AIS_SST?stringtype=unspecified
spring.datasource.username=coffee13102006
spring.datasource.password=nata155630
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - ???????? ?????????
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwtSecret=Pjd0avz4jDIZ4ykhYVRpyQMvvGajTiNli3a5h9tEzHPpNJF5vyzVRDmIn3Y98uuF4bEJyh1EVEuEeIvghXfTIt
app.jwtExpirationMs=86400000
app.jwtRefreshExpirationMs=604800000
# Logging
# ??????????? ? ?????? ??????
logging.level.root=WARN
logging.level.org.springframework.web=INFO
logging.level.org.example.ais_sst=INFO
logging.level.org.springframework.security=WARN

# Hibernate ? ?????? ????? ????? ??????????
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
spring.jpa.show-sql=false

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

app.upload.dir=uploads/events
app.upload.account-requests-dir=uploads/account_creating_requests_avatars
users-dir=uploads/users
sectors-dir=uploads/sectors

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=5000ms
spring.data.redis.client-type=lettuce

spring.data.redis.lettuce.pool.max-wait=-1ms

# ==============================================
# Redis TTL Settings
# ==============================================
app.redis.default.ttl=3600
app.redis.token.ttl.access=900
app.redis.token.ttl.refresh=604800
spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=5

logging.file.path=/var/logs/
logging.file.name=${logging.file.path}/application.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%thread] %-40.40c{1.} : %m%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%thread] %-40.40c{1.} : %m%n

# Actuator ??? ??????
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.slo.http.server.requests=10ms,100ms,1s

server.compression.enabled=false
server.tomcat.buffer-size=262144          # 256 KB
server.tomcat.max-http-post-size=20MB
server.tomcat.max-swallow-size=20MB

# ??????? ??? ?????? ?? Nginx
server.forward-headers-strategy=framework

# ?????????? ?????????
server.servlet.session.timeout=30m
spring.mvc.async.request-timeout=300000

websocket.redis.channel=websocket:notifications


# ?????? Grafana pa3),%$m[.B&~#UL9e~}6zE;%}X?!;
