# Локальный профиль
spring.application.name=AIS_SST
server.port=8080
  
  # Database - localhost
spring.datasource.url=jdbc:postgresql://localhost:5432/AIS_SST?stringtype=unspecified
spring.datasource.username=coffee13102006
spring.datasource.password=nata155630
spring.datasource.driver-class-name=org.postgresql.Driver
  
  # JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
  
  # JWT
app.jwtSecret=Pjd0avz4jDIZ4ykhYVRpyQMvvGajTiNli3a5h9tEzHPpNJF5vyzVRDmIn3Y98uuF4bEJyh1EVEuEeIvghXfTIt
app.jwtExpirationMs=86400000
app.jwtRefreshExpirationMs=604800000
  # Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.example.ais_sst=DEBUG
logging.level.org.hibernate.SQL=DEBUG
  
  # Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

