# ????? ????????? (?? ??????????????!)
spring.application.name=AIS_SST

# JWT (????? ???????? ??????)
app.jwtSecret=mySecretKeyForJWTGenerationWithAtLeast32CharactersLong2024!
app.jwtExpirationMs=86400000

# Logging
logging.level.org.springframework.security=INFO
logging.level.org.example.ais_sst=INFO

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml