# ????? ????????? (?? ??????????????!)
spring.application.name=AIS_SST

# JWT (????? ???????? ??????)
app.jwtSecret=Pjd0avz4jDIZ4ykhYVRpyQMvvGajTiNli3a5h9tEzHPpNJF5vyzVRDmIn3Y98uuF4bEJyh1EVEuEeIvghXfTIt
app.jwtExpirationMs=86400000
app.jwtRefreshExpirationMs=604800000
app.points.organizer=5
app.points.participant=2

# Logging
logging.level.org.springframework.security=INFO
logging.level.org.example.ais_sst=INFO

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

logging.file.path=/var/logs/

app.upload.dir=uploads/events
app.upload.account-requests-dir=uploads/account_creating_requests_avatars
users-dir=uploads/users
sectors-dir=uploads/sectors  # ?????????

app.redis.cache.sector.ttl=3600

app.cache.sector.ttl=3600
app.cache.photo.ttl=86400

yandex.postbox.access-key=${YANDEX_CLOUD_API_KEY:your-key-here}
yandex.postbox.secret-key=${YANDEX_CLOUD_API_KEY:your-key-here}
yandex.postbox.from-email=noreply@ais-sst.ru
yandex.postbox.region=ru-central1
yandex.postbox.endpoint=https://ses.yandexcloud.net

websocket.redis.channel=websocket:notifications
